### ISSUE TITLE
Process sometimes hangs on failure

### ISSUE THREAD

**Issue by pierotofy** [dronemapper-io/micmac#6]
Sometimes when an error occurs:

```
-------------------------------------------------------------
|       (Elise's)  LOCATION :
|
| Error was detected
|          at line : 992
|          of file : /var/www/micmac/src/util/dates.cpp
-------------------------------------------------------------
Bye  (press enter)
```

The "Press enter" keeps the process waiting for user input. But since this is running programmatically, the process never ends. Perhaps there's a flag to disable interactive mode.

**Comment by dronemapper-io** [comment]
https://github.com/dronemapper-io/micmac/commit/84c1f4e084a8fd84a8e529f8c24b2bf0d34abe3b is an additional fix to remove a rogue getChar on a warning message. Closing for now
